name: Deploy 1ppc

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0' # Укажите нужную версию Node.js

      - name: Install dependencies
        run: cd ./frontend && npm install

      - name: Build app
        run: cd ./frontend && npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_IP }} # IP-адрес вашего VPS
          username: ${{ secrets.VPS_USERNAME }} # Имя пользователя на VPS
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Приватный SSH-ключ
          script: |
            cd /root/www/typography
            git pull origin main
            cd /root/www/typography/frontend
            npm install
            npm run build
            pm2 restart front